baseURL = "https://lanjm1.github.io/"
defaultContentLanguage = "zh"
locale = "zh-Hans"
title = "Jiaming.log"
theme = "dream"

hasCJKLanguage = true
enableRobotsTXT = true

[params]
  lightTheme = "emerald"
  darkTheme = "forest"

  author = "Jiaming"
  avatar = "img/personal/avatar.jpg"
  description = "记录研究、工具、阅读与生活。"
  headerTitle = "Jiaming.log"

  siteStartYear = 2026

  stickyNav = true
  reorderNavItems = ["about", "search", "posts", "categories", "tags"]

  showTableOfContents = true
  imageZoomableInPost = true
  showPrevNextPost = true
